pipeline {
    agent any
        tools{
            maven "maven-4.0.0"
        }   
    stages {
        stage('Maven clean') {
            steps {
                script {
                    // Limpar e compilar o projeto usando Maven
                    sh 'mvn clean install'
                }
            }
        }
        stage('maven build') {
            steps {
                script {
                    // Executar os testes do projeto
                    sh 'mvn test'
                    }
                }
            }
        }
}
